export const type = {
    loading: '[USER] LOADING',
    getDepartment:'[DEPARTMENT] GET',
    newDepartment:'[DEPARTMENT] NEW',
    updateDepartment:'[DEPARTMENT] UPDATE',
    deleteDepartment:'[DEPARTMENT] DELETE',
    cleanDepartment:'[DEPARTMENT] CLEAN',
    selectDepartment:'[DEPARTMENT] SELECT',
    cleanRoles:'[ROLES] CLEAN',
    getRoles: '[ROLES] GET',
    selectRol: '[ROLES] SELECT',
    newRoles: '[ROLES] NEW',
    updateRoles: '[ROLES] UPDATE',
    deleteRoles: '[ROLES] DELETE',
    getUsers: '[USER] GET',
    newUser: '[USER] NEW',
    selectUser: '[USER] SELECT',
    cleanUser: '[USER] CLEAN',
    updateUser: '[USER] UPDATE',
    newTicket: '[TICKET] NEW',
    getTickets: '[TICKET] GET',
    getHistory: '[TICKET] HISTORY',
    updateTicket: '[TICKET] UPDATE',
    changeTicketUser: '[TICKET] TICKET_USER',
    selectTicket: '[TICKET] SELECT',
    cleanTicket: '[TICKET] CLEAN',
    resetTicket: '[TICKET] RESET',
    resetDepartments: '[DEPARTMENT] RESET',
    resetRol: '[ROL] RESET',
    resetUser: '[USER] RESET',
    createHistory: '[TICKET] CREATE_HISTORY',
    pageHistoryTicket: '[TICKET] PAGE_HISTORY',
    pageHistoryTicketAdd: '[TICKET] PAGE_HISTORY_ADD',
    loadRol: '[ROL] LOADING',
    loadDepartment: '[DEPARTMENT] LOADING'
}